import re


def apply_sender_signature(
    draft: str,
    sender_name: str,
    sender_title: str,
    sender_company: str,
) -> str:
    """
    Apply the configured sender signature
    to an AI-generated reply draft.

    The final sender signature is controlled
    by application configuration rather than
    by the AI-generated signature.

    This function only transforms text.
    It never sends email.
    """

    signature_lines = [
        sender_name,
        sender_title,
        sender_company,
    ]

    signature = "\n".join(
        line.strip()
        for line in signature_lines
        if line and line.strip()
    )

    if not signature:
        return draft

    result = draft

    # First replace known placeholders.
    result = result.replace(
        "[Your Name]",
        sender_name,
    )

    result = result.replace(
        "[Your Title]",
        sender_title,
    )

    result = result.replace(
        "[Your Company]",
        sender_company,
    )

    # The final signature must be controlled
    # by configuration, not by AI output.
    #
    # Examples that may be generated by AI:
    #
    # Best regards,
    # Sales Team
    #
    # Best regards,
    # Zhao Xin
    #
    # Best regards,
    # [Your Name]
    # [Your Title]
    # [Your Company]
    #
    # In every case, everything after the
    # final sign-off is replaced with the
    # configured sender signature.

    signoff_pattern = re.compile(
        r"(?im)^"
        r"(Best regards,?|Kind regards,?|Regards,?|Sincerely,?)"
        r"\s*$"
    )

    matches = list(
        signoff_pattern.finditer(result)
    )

    if matches:
        last_signoff = matches[-1]

        content_before_signature = (
            result[
                :last_signoff.end()
            ].rstrip()
        )

        return (
            content_before_signature
            + "\n"
            + signature
        )

    # Fallback:
    # if the AI did not generate a recognized
    # sign-off, keep the reply body unchanged
    # except for placeholder replacement.
    return result